import sanitizeHtml from "sanitize-html";

/**
 * Strict HTML allowlist for model-generated post bodies.
 *
 * Threat model: the post is generated by an LLM, then dropped verbatim into a
 * static file served to every visitor. A successful prompt injection (or a
 * model error) that emits <script>, <iframe>, or an inline event handler
 * would execute on every reader's browser. Sanitization is the defense.
 *
 * Rules:
 *   - Allow only the tags the tool schema declared.
 *   - Allow the inline-cta block structure with the specific class names we use.
 *   - Strip every event handler (`on*`), `javascript:` URIs, and data URIs.
 *   - Force <a target="_blank"> to also carry rel="noopener noreferrer".
 */
const POST_BODY_OPTIONS: sanitizeHtml.IOptions = {
  allowedTags: [
    "h2", "h3", "h4",
    "p", "ul", "ol", "li",
    "blockquote", "pre", "code",
    "strong", "em", "a", "hr",
    "div",
  ],
  allowedAttributes: {
    a: ["href", "target", "rel"],
    div: ["class"],
    h4: [],
    p: [],
  },
  allowedClasses: {
    div: ["inline-cta", "inline-cta-text", "inline-cta-eyebrow"],
    a: ["btn"],
  },
  allowedSchemes: ["http", "https", "mailto"],
  allowedSchemesByTag: { a: ["http", "https", "mailto"] },
  allowedSchemesAppliedToAttributes: ["href"],
  allowProtocolRelative: false,
  // Strip any tag we didn't list, including its contents — defense in depth
  // against <script>foo</script> where leaving "foo" behind would still be wrong.
  nonTextTags: ["script", "style", "iframe", "object", "embed", "form", "input", "button", "textarea", "svg", "math"],
  transformTags: {
    a: sanitizeHtml.simpleTransform("a", { rel: "noopener noreferrer" }, true),
  },
  // Disallow ALL on* attributes everywhere — sanitize-html does this by default
  // when they're not in allowedAttributes, but be explicit:
  disallowedTagsMode: "discard",
};

const LEDE_OPTIONS: sanitizeHtml.IOptions = {
  // The lede is plain text in the template; allow only the simplest inline tags
  // in case the model gets fancy.
  allowedTags: ["em", "strong"],
  allowedAttributes: {},
  allowedSchemes: [],
  disallowedTagsMode: "discard",
};

export function sanitizeBody(html: string): string {
  return sanitizeHtml(html, POST_BODY_OPTIONS);
}

export function sanitizeLede(text: string): string {
  return sanitizeHtml(text, LEDE_OPTIONS);
}

/**
 * Loud failure if sanitization would have silently stripped a script-y construct.
 * Run this AFTER sanitizeBody and BEFORE writing — if the diff is non-trivial
 * we want the cron to abort, log, and not commit a half-bad post.
 */
export function assertNoDangerousMarkup(originalHtml: string, sanitizedHtml: string): void {
  const dangers = [
    /<script\b/i,
    /<iframe\b/i,
    /<object\b/i,
    /<embed\b/i,
    /\son[a-z]+\s*=/i, // onClick=, onerror=, etc.
    /javascript:/i,
    /data:\s*text\/html/i,
  ];

  for (const pattern of dangers) {
    if (pattern.test(originalHtml)) {
      throw new Error(
        `Model output contained dangerous markup matching ${pattern}. Aborted before commit. ` +
          `Sanitized version (no longer dangerous): ${sanitizedHtml.slice(0, 200)}...`,
      );
    }
  }
}
